# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  create_space:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Create workspace test"
      - run: echo "Trying out workspaces" > Go/echo-output
      - run: ls
      - persist_to_workspace:
          root: Go
          paths:
            - ./*
  test_space:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Attach workspace test"
      - attach_workspace:
          at: Go
      - run: ls Go
      - run: cat Go/echo-output
  
  build_application:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Building application"
      - run: echo $PKTEST

workflows:
  version: 2
  flow_one:
    jobs:
      - create_space
      - test_space:
          requires:
            - create_space
  flow_two:
    jobs:
      - build_application:
          context: CiTest

  programmed:
    triggers:
      - schedule:
          cron: "30 19 * * *" # Ejecutarlo a las 7:30 de la tarde todos los dias (minutos, horas, dia del mes (1,31), mes (1,12), dia de la semana (0 (domingo),6))
    jobs:
      - create_space