# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  create_space:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Create workspace test"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
      - run: ls
      - persist_to_workspace:
          root: Go
          paths:
            - ./*
     
  
  test_space:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Attach workspace test"
      - run: ls
      - attach_workspace:
          at: Go
  
  build_application:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo "Building application"

workflows:
  version: 2
  flow_one:
    jobs:
      - create_space
      - test_space:
          requires:
            - create_space
  flow_two:
    jobs:
      - build_application